// generated by Fast Light User Interface Designer (fluid) version 1.0311

#ifndef fluid_h
#define fluid_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Return_Button.H>

class CrashDlg {
public:
  Fl_Double_Window* makeWin();
  Fl_Text_Display *msg;
};
#endif
